OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-tdqfro61NniG2LZd5394E5F28c51419d8b4dE7Db5a6105C4"
GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "d:/workspace/openai-quickstart/guoly/openai-quickstart/openai-translator/ai_translator/tests/test.pdf"
  file_format: "PDF"
  target_language: "中文"
