model_name: "gpt-3.5-turbo"
input_file: "d:/workspace/openai-quickstart/guoly/openai-quickstart/openai-translator/tests/test.pdf"
output_file_format: "markdown"
source_language: "English"
target_language: "Chinese"